# Generated by Django 3.1 on 2020-09-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('olaviat', models.CharField(max_length=20, verbose_name='اولویت')),
                ('vaziat', models.CharField(default='باز', max_length=20, verbose_name='وضعیت')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['-vaziat'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=150, verbose_name='ایجاد کننده')),
                ('task_message', models.TextField(verbose_name='پاسخ')),
                ('tiket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tiket', verbose_name='مربوط به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ReplyTiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(verbose_name='پاسخ')),
                ('tiket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tiket', verbose_name=' پاسخ به')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ['wuser'],
            },
        ),
        migrations.CreateModel(
            name='ReplyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(verbose_name='پاسخ')),
                ('Task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.task', verbose_name=' پاسخ به')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ['wuser'],
            },
        ),
    ]
