# Generated by Django 3.1 on 2020-09-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inqueries',
            options={'verbose_name': 'تیکت ', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='olaviat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='vaziat',
            field=models.CharField(default='باز', max_length=20),
        ),
    ]
