# Generated by Django 3.1 on 2020-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200903_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='olaviat',
            field=models.CharField(max_length=20, verbose_name='اولویت'),
        ),
    ]
