# Generated by Django 3.1 on 2020-09-24 13:45

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200924_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytask',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replytiket',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replytiket',
            name='tiket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.tiket', verbose_name=' پاسخ به'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tiket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.tiket', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
