# Generated by Django 3.1 on 2020-09-04 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200903_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inqueries',
            options={'ordering': ['-vaziat'], 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(verbose_name='پاسخ')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.inqueries', verbose_name=' پاسخ به')),
                ('wuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
            ],
            options={
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ['wuser'],
            },
        ),
    ]
