# Generated by Django 3.1 on 2020-09-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_inqueries_erja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inqueries',
            name='erja',
        ),
    ]
